name: Render CV

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install RenderCV
        run: pip install "rendercv[full]"

      - name: Generate CV PDF
        run: rendercv render src/Tien_CV.yaml

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-pdf-cv
          path: rendercv_output/
